### ISSUE TITLE
Compiled Carbonator require Visual Studio

### ISSUE THREAD

**Issue by v10nchan** [CryptonZylog/carbonator#20]
I have a compiled Carbonator with nuget, and wish to put to other servers(Windows 2003), it was trying to look for VS just-in-time. I tried to run with or without console/verbose mode, it fails too. 

Is there any way to disable just-in-time flag while compiling? Thanks.

**Comment by CryptonZylog** [comment]
I am not sure what you are trying to do exactly here (compile for Win2003?). I don't have a plan to support Windows XP/2003 (since they are not even officially supported by MS), and later versions of .NET may not be even supported on that platform. I haven't been maintaining the command-line build script as of lately, so I should probably get on that ;)

**Comment by v10nchan** [comment]
thanks for super fast response. I'm quite new about Windows servers. I would like to use Carbonator on production servers, which means not adding extra package would be best. I was hopping compiling Carbonator as EXE with required library would help. 
Do I need .NET on W2003 to be able to run Carbonator? Whats the minimum version of .NET I should be using?

**Comment by CryptonZylog** [comment]
See pre-compiled releases here: https://github.com/CryptonZylog/carbonator/releases

Yes, you need .NET installed on Win2003 since it is not included with the OS. v1.5 requires .NET 4.0.

**Comment by v10nchan** [comment]
Thanks a lot, v1.6 work on W2003 testing server, it has .NET 4.0. 
May I ask whats .NET min requirement for v2.x?

**Comment by CryptonZylog** [comment]
.NET 4.5.1

**Comment by v10nchan** [comment]
Thanks a lot.
