### ISSUE TITLE
Adding "*" Instances

### ISSUE THREAD

**Issue by Cylindric** [CryptonZylog/carbonator#5]
Hi. I've just started looking at using Carbonator to ship perfmon data to ElasticSearch. We run many SQL databases on many SQL instances, so maintaining the configuration file with lots of individual counters is quite hard. Would it be possible to specify an instance of "*", a bit like in perfmon itself, and have Carbonator then create one report for each returned instance?

For example, if we have a changing number of drives, instead of this:

    <counters>
      <add path="%HOST% LogicalDisk FreeSpace C" category="LogicalDisk" counter="% Free Space" instance="C:" />
      <add path="%HOST% LogicalDisk FreeSpace D" category="LogicalDisk" counter="% Free Space" instance="D:" />
      <add path="%HOST% LogicalDisk FreeSpace E" category="LogicalDisk" counter="% Free Space" instance="E:" />
      <add path="%HOST% LogicalDisk FreeSpace F" category="LogicalDisk" counter="% Free Space" instance="F:" />
    </counters>

It would be nice to be able to specify this:

	<counters>
      <add path="%HOST% LogicalDisk FreeSpace %INSTANCE%" category="LogicalDisk" counter="% Free Space" instance="*" />
    </counters>

This would be especially useful on clusters, where the drives can move about from node to node.

**Comment by CryptonZylog** [comment]
Should be doable, I will need to test this out. That is, if you plug in an external drive, Carbonator will need to poll (if that's a good way) the instance names ever so often to pick up on the new instance, and whenever system decides that counter is no longer available.

**Comment by ShijunK** [comment]
It will be great if the enhancement also support wildcard/regex. I am thinking about "Process" category. which have each process as separate instance. I'd like to monitor certain processes, says any processes whose name starts with "pg". Is it reasonable?

**Comment by CryptonZylog** [comment]
Yes, regex sounds reasonable (since .+ is a wildcard in regex anyway).

**Comment by CryptonZylog** [comment]
There is a bit of annoyance I am running into with this. ``PerformanceCounterCategory`` has a method to return instance names - ``[GetInstanceNames()](https://msdn.microsoft.com/en-us/library/system.diagnostics.performancecountercategory.getinstancenames%28v=vs.110%29.aspx)``. Unfortunately, there seems to be a performance hit when calling this method. Possibly because it has to enumerate all counters in the category, then their instance names.

While it is certainly possible to add the ability to load instance names based on a wildcard (regex match), we may need to allow it to do so only at **start-up**. If your instances change during Carbonator operation, Carbonator would have to be restarted to pick up new instances.

**Comment by CryptonZylog** [comment]
Resolved in v1.5
